version: '3'
services:
  eqtl_flask:
    image: krrome/eqtlbrowser_docker
    ports:
      - "5000:80"
    environment:
      - STATIC_PATH=/app/app/static
    links:
      - eqtl_mongodb
  eqtl_mongodb:
    image: "mongo:3.4.10"
    command: --dbpath /usr/share/mongo_data --wiredTigerEngineConfigString="cache_size=200MB"
    #volumes:
    # - /Users/roman/ebrowser/mongodb_new_data:/usr/share/mongo_data
